### ISSUE TITLE
Uploaded classifications aren't really uploaded

### ISSUE THREAD

**Issue by murraycu** [murraycu/ios-galaxyzoo#1]
Although the zooniverse server responds to our POSTs with 201 (Created), it doesn't seem to really be accepting them. For instance, they don't show up in my profile page
  http://www.galaxyzoo.org/#/profile
though I am supplying the correct name and api_key in the Authorization header, correctly I think.

These request have the User-Agent set as "murrayc.com-ios-galaxyzoo" so they should be easy to find on the server's side. Maybe someone there can see what the server doesn't like about them.

For instance, this is the body (content) of the request:
<pre>
%5Bsubject_ids%5D%5B%5D=5500598269736d5162160800&classification%5Bannotations%5D%5B0%5D%5Bsloan_singleband-0%5D=a-1&classification%5Bannotations%5D%5B1%5D%5Bsloan_singleband-1%5D=a-1&classification%5Bannotations%5D%5B2%5D%5Bsloan_singleband-2%5D=a-1&classification%5Bannotations%5D%5B3%5D%5Bsloan_singleband-3%5D=a-0&classification%5Bannotations%5D%5B4%5D%5Bsloan_singleband-9%5D=a-1&classification%5Bannotations%5D%5B5%5D%5Bsloan_singleband-10%5D=a-1&classification%5Bannotations%5D%5B6%5D%5Bsloan_singleband-4%5D=a-2&classification%5Bannotations%5D%5B7%5D%5Bsloan_singleband-5%5D=a-1&classification%5Bannotations%5D%5B8%5D%5Bsloan_singleband-11%5D=a-1&classification%5Bannotations%5D%5B9%5D%5Buser_agent%5D=murrayc.com-ios-galaxyzoo
</pre>

And these are the headers that are set:

<pre>
    Authorization = "REDACTED_BUT_I_AM_QUITE_SURE_IT_IS_CORRECT";
    "Content-Length" = 734;
    "Content-Type" = "application/x-www-form-urlencoded";
    "User-Agent" = "murrayc.com-ios-galaxyzoo";
</pre>

Something must be wrong with the POST request that we make in uploadClassifications:
https://github.com/murraycu/ios-galaxyzoo/blob/master/ios-galaxyzoo/client/ZooniverseClient.m#L517
though it seems to be doing the same thing as the similar (working) code in the Android app:
https://github.com/murraycu/android-galaxyzoo/blob/master/app/src/main/java/com/murrayc/galaxyzoo/app/provider/client/ZooniverseClient.java#L305

**Comment by edpaget** [comment]
@murraycu I guess it's probably just a typo in your post, but do you have classification prefixing [subject_ids]?

**Comment by murraycu** [comment]
Ed, vast thanks for that sanity check. That was the problem. I thought it would turn out to be something simple, and of course I had the "classification" prefix in my test code.

**Comment by murraycu** [comment]
Ed, in case you know of any other interested iPhone developers, I've prepare some things that people might like to implement while I'm off on holiday for a couple of weeks: http://www.murrayc.com/permalink/2015/05/22/galaxy-zoo-iphone-app-developers-welcome/

Maybe I should mention that on talk.galaxyzoo.org, but I'm not sure where.
