### ISSUE TITLE
List is showing subjects I haven't yet been asked to classify

### ISSUE THREAD

**Issue by vrooje** [murraycu/ios-galaxyzoo#11]
Not sure if this is intended behavior or not, but the list is showing me objects in the queue as well as those I've already classified. I think it shouldn't show any images I haven't yet classified, right?

**Comment by murraycu** [comment]
The app caches subjects in advance so you don't need to be online to get the next subject. It should show a little tick icon on subjects that you have classified (these should appear at the top), and it should show a little up icon on the classified subjects that have been uploaded. Like this:
https://github.com/murraycu/ios-galaxyzoo/blob/master/screenshots_for_translators/screenshot_iphone6_list_portrait.png

That's the same as my Android app:
https://github.com/murraycu/android-galaxyzoo/blob/master/screenshots_for_translators/galaxyzoo_translator_screenshot_list.png

**Comment by vrooje** [comment]
I didn't realize the Android app did this too (I don't have any Android devices)!

It's just that we don't show the upcoming queue on the website and out of an abundance of caution I'm trying to consider ways this might affect the classifications somehow. But perhaps I'm being paranoid. Wondering if @willettk or @chrislintott might want to weigh in?

**Comment by murraycu** [comment]
Note that it only lets you view (fully) subjects that you've classified already. It's mainly just to show that there really are subjects cached and ready to be classified.

**Comment by willettk** [comment]
Yeah - all you see is the thumbnails of galaxies, but you can't click
through to examine or select a particular subject to classify. I can't
think of a way that it would risk changing classification behavior.

**Comment by chrislintott** [comment]
I worry that people will only classify the 'interesting galaxies' (or the ellipticals to speed progress). If you have to complete the set to get more then I don't think it's a problem.

**Comment by willettk** [comment]
That's right, @chrislintott. You get a short preview of the next few
galaxies in the queue, but there's no way for users to select a particular
galaxy or skip ahead to something more interesting.

**Comment by vrooje** [comment]
In that case, as we are all in agreement that I'm being paranoid, I'll close this. :)
