### ISSUE TITLE
Login appears to have no effect

### ISSUE THREAD

**Issue by vrooje** [murraycu/ios-galaxyzoo#14]
I didn't get an error message when I tried to log in, but it didn't succeed either; I had assumed it wasn't yet supported, but perhaps not!

**Comment by murraycu** [comment]
Do you definitely not see the classifications on your profile? For instance:
http://www.galaxyzoo.org/#/profile/recents/1

And does it still ask you to login?

**Comment by murraycu** [comment]
Ah, I see the same problem now too. Clicking "Login" on the login form now just does nothing. I'll investigate.

And now I see that I did indeed add a Login button on the bottom toolbar.

**Comment by murraycu** [comment]
Actually, at the moment, it does close the login screen when the password was accepted. I was typing my password wrongly. I wonder if it's the same for you - please double-check your password by logging in to the website with it again. Or maybe you have special characters in your password that the app isn't coping with.

**Comment by vrooje** [comment]
Yes, it did close the login screen (no special characters) but I then can't tell whether I'm actually logged in, and if I keep classifying I get the prompt to log in again. I've checked and the galaxies I recently classified there aren't showing up on my profile.

Should I check in our classification DB whether any classifications from the app are listed as from me?

**Comment by murraycu** [comment]
Let's look at this again after I've released a new version (soonish) that makes it clearer when you are logged in. Its understandably confusing right now.

I think you have logged in successfully already. Note that only the classifications done after your login will  show up on your profile. They are showing up for me. But let's check that again with the new version.

**Comment by murraycu** [comment]
I have released 0.4 to the TestFlight system today. Hopefully you got an email about that or TestFlight offered to update the app for you.

Here are the changes in 0.4:
https://github.com/murraycu/ios-galaxyzoo/blob/master/NEWS

**Comment by murraycu** [comment]
@vrooje , Does login work for you now?

**Comment by vrooje** [comment]
Yes, it works and I've verified that galaxies I'm classifying on the app do show up on my online profile. Hurray!

**Comment by murraycu** [comment]
Thanks.
