### ISSUE TITLE
login with an iPhone 4S: can't close keyboard or submit

### ISSUE THREAD

**Issue by vrooje** [murraycu/ios-galaxyzoo#18]
The app is working really well so far on my 4S, though when I try to login the keyboard blocks the "Sign In" link: 

![img_2607](https://cloud.githubusercontent.com/assets/2357126/11367198/06447396-92aa-11e5-9e4e-9329fedd2412.PNG)

I then can't get the keyboard to disappear (tapping outside the text boxes just brings up the "forgot password" page, even when I'm tapping very far from that link), and I didn't have a "Go" option from the keyboard, so I haven't been able to log in.

**Comment by murraycu** [comment]
Thanks. I had seen that on a 4S but had forgotten about it.

It now uses Next and Go on the keyboard, and the buttons are only clickable on the actual text. This will be in the next version that I will release in a day or so.

**Comment by murraycu** [comment]
Please try again with version 0.10 which should now be available via the TestFlight app.

**Comment by vrooje** [comment]
Works!

**Comment by murraycu** [comment]
Thanks. As a regular iPhone/iPad user, maybe you also have an opinion about this: https://github.com/murraycu/ios-galaxyzoo/issues/12
